### ISSUE TITLE
Devices are not listed

### ISSUE THREAD

**Issue by rwiebe** [hausbus/ioBroker.hausbus_de#25]
After a powerloss, our NAS had some problems. 
After manually bringing all containers, iobroker works fine, but not the hausbus.de adapter

in IObroker => objects > hausbus_de
there should be listes all discoverable devices, but i can only find to trigger to scan to devices.

in the Protocol i can see like this messages

```
hausbus_de.0 | 2023-09-15 20:10:46.897 | info | input event event_released, state = true <- UNKNOWN_DEVICE (1443).Eingänge_ID22, moduleType=undefined
hausbus_de.0 | 2023-09-15 20:10:15.192 | info | brightness sensor status: 0.90, state = <- UNKNOWN_DEVICE (1443).Helligkeitssensoren_ID23, moduleType=undefined
```
therefore i have no backup of the container with an old version.

**Versions:**  
iobroker: latest-8 (8.1.09
 - Adapter version: 1.2.11
 - JS-Controller version: 4.0.24
 - Node version: v18.17.1
 - Operating system: docker container

**Comment by hausbus** [comment]
What happens if you click on search devices?
If you only see incoming events like in your example from the brightness sensor then it's typically some kind of firewall problem.
Was the network changed somehow? New subnet mask?
To have more information please go to the adapter and enable trace level debug by changing to developer view. Afterwards scan for devices and then export the logs and send to ***@***.***
________________________________
From: rwiebe ***@***.***>
Sent: Friday, September 15, 2023 8:15:03 PM
To: hausbus/ioBroker.hausbus_de ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hausbus/ioBroker.hausbus_de] Devices are not listed (Issue #25)


After a powerloss, our NAS had some problems.
After manually bringing all containers, iobroker works fine, but not the hausbus.de adapter

in IObroker => objects > hausbus_de
there should be listes all discoverable devices, but i can only find to trigger to scan to devices.

in the Protocol i can see like this messages

hausbus_de.0 | 2023-09-15 20:10:46.897 | info | input event event_released, state = true <- UNKNOWN_DEVICE (1443).Eingänge_ID22, moduleType=undefined
hausbus_de.0 | 2023-09-15 20:10:15.192 | info | brightness sensor status: 0.90, state = <- UNKNOWN_DEVICE (1443).Helligkeitssensoren_ID23, moduleType=undefined


therefore i have no backup of the container with an old version.

Versions:
iobroker: latest-8 (8.1.09

  *   Adapter version: 1.2.11
  *   JS-Controller version: 4.0.24
  *   Node version: v18.17.1
  *   Operating system: docker container
